insert into barrelWaterBrand(id,barrelWaterBrandName) values(0,'农夫山泉');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(1,'怡宝');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(2,'乐百氏');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(3,'景田');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(4,'娃哈哈');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(5,'雀巢');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(6,'屈臣氏');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(7,'哇哈哈');
insert into barrelWaterBrand(id,barrelWaterBrandName) values(8,'其他');